// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_lNKnI71BMo-eIGYWkF9TZIRu94Esso',
    appId: '1:661875192859:web:b1aa8529c30490cca5b4be',
    messagingSenderId: '661875192859',
    projectId: 'prettypie',
    authDomain: 'prettypie.firebaseapp.com',
    storageBucket: 'prettypie.firebasestorage.app',
    measurementId: 'G-DEW3RJ3353',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2uZOQFPLHbVq4ZRmq-JD8y6X2QHAjjw',
    appId: '1:661875192859:android:4fc1cec8c3c84d27a5b4be',
    messagingSenderId: '661875192859',
    projectId: 'prettypie',
    storageBucket: 'prettypie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9z4WMDM4wYWIqxzAOsY9VzmIOhe0yIWM',
    appId: '1:661875192859:ios:f3852c19de17e08da5b4be',
    messagingSenderId: '661875192859',
    projectId: 'prettypie',
    storageBucket: 'prettypie.firebasestorage.app',
    iosBundleId: 'com.example.prettypieMyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9z4WMDM4wYWIqxzAOsY9VzmIOhe0yIWM',
    appId: '1:661875192859:ios:f3852c19de17e08da5b4be',
    messagingSenderId: '661875192859',
    projectId: 'prettypie',
    storageBucket: 'prettypie.firebasestorage.app',
    iosBundleId: 'com.example.prettypieMyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_lNKnI71BMo-eIGYWkF9TZIRu94Esso',
    appId: '1:661875192859:web:544eedb41ba9a750a5b4be',
    messagingSenderId: '661875192859',
    projectId: 'prettypie',
    authDomain: 'prettypie.firebaseapp.com',
    storageBucket: 'prettypie.firebasestorage.app',
    measurementId: 'G-G226F4CZS4',
  );
}
