// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjGjMKnZ3zDdSFA2ImrvVnnN4qCqRI-4',
    appId: '1:947969904935:web:f61e7c628511b45a25d902',
    messagingSenderId: '947969904935',
    projectId: 'mygov-ai',
    authDomain: 'mygov-ai.firebaseapp.com',
    storageBucket: 'mygov-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKPKwBvGgvy58iaJP9dlRZ6zq6rCw19E',
    appId: '1:947969904935:android:b5a489c1d406f33725d902',
    messagingSenderId: '947969904935',
    projectId: 'mygov-ai',
    storageBucket: 'mygov-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9UwUSI_fQ-_gTayemTlCtShTYtu-IoQo',
    appId: '1:947969904935:ios:9baba0a4d2d10f7525d902',
    messagingSenderId: '947969904935',
    projectId: 'mygov-ai',
    storageBucket: 'mygov-ai.firebasestorage.app',
    iosBundleId: 'com.example.prettypieMyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9UwUSI_fQ-_gTayemTlCtShTYtu-IoQo',
    appId: '1:947969904935:ios:9baba0a4d2d10f7525d902',
    messagingSenderId: '947969904935',
    projectId: 'mygov-ai',
    storageBucket: 'mygov-ai.firebasestorage.app',
    iosBundleId: 'com.example.prettypieMyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsjGjMKnZ3zDdSFA2ImrvVnnN4qCqRI-4',
    appId: '1:947969904935:web:39785f49f86d71a525d902',
    messagingSenderId: '947969904935',
    projectId: 'mygov-ai',
    authDomain: 'mygov-ai.firebaseapp.com',
    storageBucket: 'mygov-ai.firebasestorage.app',
  );

}